name: Bot + Cloudflare Tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"   # تشغيل كل 6 ساعات

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Create cloudflared directory
        run: mkdir -p ~/.cloudflared

      - name: Add Tunnel JSON
        run: echo "${{ secrets.CLOUDFLARE_TUNNEL_JSON }}" > ~/.cloudflared/44dac3e9-2dce-4327-b02c-f03bf346613e.json

      - name: Add Tunnel config
        run: echo "${{ secrets.CLOUDFLARE_TUNNEL_CONFIG }}" > ~/.cloudflared/config.yml

      - name: Start Cloudflare Tunnel
        run: cloudflared tunnel run 44dac3e9-2dce-4327-b02c-f03bf346613e &

      - name: Start Flask Bot
        run: python bot.py
